name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build-n-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcppunit-dev g++ libopenmpi-dev openmpi-bin libgtest-dev

      - name: Compile the program with MPI
        run: mpic++ -o mpi_program hockeyGame.cpp

      - name: Compile and run tests
        run: |
          mpic++ test.cpp -lgtest -lgtest_main -o test
          chmod +x test
          mpiexec -n 1 ./test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test
